name: Clang 17-18

on:
  workflow_run:
    workflows: [Generate single-include header]
    types: 
      - completed

jobs:
  clang:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        version: [16, 17, 18]
        modules: [false, true]
        built_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true # recursive

    - name: Install Ninja
      run: /usr/bin/ninja --version || sudo apt-get install ninja-build

    - name: Install clang ${{ matrix.version }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.version }}
        sudo apt install clang-tools-${{ matrix.version }} libstdc++-13-dev

    - name: Configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} "/usr/bin/clang-${{ matrix.version }}")
        set(ENV{CXX} "/usr/bin/clang++-${{ matrix.version }}")

        execute_process(
          COMMAND cmake
            -S .
            -B build
            -G Ninja
            -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -D ECS_COMPILE_AS_MODULE=${{ matrix.modules }}
            -D CMAKE_MAKE_PROGRAM=/usr/bin/ninja
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()


    - name: Build
      shell: cmake -P {0}
      run: |
        set(ENV{NINJA_STATUS} "[%f/%t %e sec] ")

        execute_process(
          COMMAND cmake --build build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "CMake build failed")
        endif()


    - name: Run tests
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)

        execute_process(
          COMMAND ctest --output-on-failure -j ${N}
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Running tests failed!")
        endif()
